import type { NextPage } from 'next'
import Head from 'next/head'

import useSWR from 'swr'

import AboutUs from '../components/aboutus'
import ContactUs from '../components/contactus'
import Footer from '../components/footer'
import Masthead from '../components/masthead'
import Skills from '../components/skills'
import TrustedBy from '../components/trustedby'
import Works from '../components/works'

const Home: NextPage = () => {
  //const fetcher = async (input: any, init?: any) => {
  //  const response = await fetch(input, init)
  //  const data = await response.json()
  //  return data
  //}
  const fetcher = (input: any, init?: any) => fetch(input, init).then(res => res.json())
  const { data } = useSWR('/api/stats', fetcher, { fallbackData: { downloads: 33388721, commits: 282 } })

  return (
    <div>
      <Head>
        <title>Eraka</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Masthead />
      <AboutUs />
      <Skills downloads={data?.downloads} commits={data?.commits} />
      <Works />
      <TrustedBy />
      <ContactUs />
      <Footer />
    </div>
  )
}

export default Home
